FROM ubuntu:18.10
MAINTAINER Kok How, Teh <kokhow.teh@taiger.com>
# Install dependencies
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y wget sudo python curl libasound2
RUN wget -q -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/11.0.1+13/90cf5d8f270a4347a95050320eef3fb7/jdk-11.0.1_linux-x64_bin.deb -P /tmp
RUN dpkg -i /tmp/jdk-11.0.1_linux-x64_bin.deb
RUN update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-11.0.1/bin/java 2
RUN update-alternatives --config java
RUN update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/jdk-11.0.1/bin/jar 2
RUN update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-11.0.1/bin/javac 2
RUN update-alternatives --set jar /usr/lib/jvm/jdk-11.0.1/bin/jar
RUN update-alternatives --set javac /usr/lib/jvm/jdk-11.0.1/bin/javac
RUN useradd -r -m -U -d /opt/tomcat -s /bin/false tomcat
RUN wget -q http://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.14/bin/apache-tomcat-9.0.14.tar.gz -P /tmp
RUN tar xf /tmp/apache-tomcat-9*.tar.gz -C /opt/tomcat
RUN rm -f /tmp/*
RUN ln -s /opt/tomcat/apache-tomcat-9.0.14 /opt/tomcat/latest
RUN chown -RH tomcat: /opt/tomcat/latest
RUN chmod o+x /opt/tomcat/latest/bin
ADD manager_context.xml /opt/tomcat/latest/webapps/manager/META-INF/context.xml
ADD host-manager_context.xml /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
RUN rm -rf /opt/tomcat/latest/webapps/docs /opt/tomcat/latest/webapps/examples
RUN apt autoremove
ADD dist /opt/tomcat/latest/webapps/ROOT/ui
ADD env-prod.js /opt/tomcat/latest/webapps/ROOT/ui/chat/chat-app/env.js
RUN chown -R tomcat:tomcat /opt/tomcat/latest/webapps/ROOT/ui
EXPOSE 22 8080 443
#ENTRYPOINT [“java”,”-Djava.security.egd=file:/dev/./urandom”,”-jar”,”/HelloRestAPI-0.0.1-SNAPSHOT.jar”]
CMD ["/opt/tomcat/latest/bin/catalina.sh", "run"]
